### ISSUE TITLE
建议支持一行可以放多个组件

### ISSUE THREAD

**Issue by xihazhiwang** [JakHuang/form-generator#1]
目前功能只支持一行一个组件，建议支持一行可以放多个组件，并且每行的组件个数是自定义的

**Comment by JakHuang** [comment]
【表单栅格】就是控制一行多个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xihazhiwang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 下午4:20
收件人:&nbsp;"JakHuang/form-generator"<form-generator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JakHuang/form-generator] 建议支持一行可以放多个组件 (#1)




目前功能只支持一行一个组件，建议支持一行可以放多个组件，并且每行的组件个数是自定义的

**Comment by xihazhiwang** [comment]
试过了，已看到，谢谢！
