### ISSUE TITLE
基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路

### ISSUE THREAD

**Issue by weizhanzhan** [JakHuang/form-generator#101]
基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路

**Comment by xuergo** [comment]
> 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路

大哥搞出来了吗

**Comment by weizhanzhan** [comment]
> > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> 
> 大哥搞出来了吗
我想的是在config中把方法定义好，然后组件中以bus的方式监听

**Comment by xuergo** [comment]
> > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > 
> > 
> > 大哥搞出来了吗
> > 我想的是在config中把方法定义好，然后组件中以bus的方式监听

大哥你是这么写的吗？
![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的

**Comment by weizhanzhan** [comment]
> > > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > > 
> > > 
> > > 大哥搞出来了吗
> > > 我想的是在config中把方法定义好，然后组件中以bus的方式监听
> 
> 大哥你是这么写的吗？
> ![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
> 你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的

你看他的example，https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue

**Comment by xuergo** [comment]
> > > > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > > > 
> > > > 
> > > > 大哥搞出来了吗
> > > > 我想的是在config中把方法定义好，然后组件中以bus的方式监听
> > 
> > 
> > 大哥你是这么写的吗？
> > ![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
> > 你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的
> 
> 你看他的example，https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue

好了
```
item1['on-success'] = (response, file, fileList) => {
							if (response.success == "true") {
								item1['file-list'] = ([{
									name: '文件',
									url: response.msg
								}])
								this.$refs.parser.$refs.elForm.model[item1.fieldAlias] = response.msg
							}
						}
```

**Comment by weizhanzhan** [comment]
> > > > > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > > > > 
> > > > > 
> > > > > 大哥搞出来了吗
> > > > > 我想的是在config中把方法定义好，然后组件中以bus的方式监听
> > > 
> > > 
> > > 大哥你是这么写的吗？
> > > ![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
> > > 你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的
> > 
> > 
> > 你看他的example，https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue
> 
> 好了
> 
> ```
> item1['on-success'] = (response, file, fileList) => {
> 							if (response.success == "true") {
> 								item1['file-list'] = ([{
> 									name: '文件',
> 									url: response.msg
> 								}])
> 								this.$refs.parser.$refs.elForm.model[item1.fieldAlias] = response.msg
> 							}
> 						}
> ```

优秀

**Comment by shitou13** [comment]
> https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue



> > > > > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > > > > 
> > > > > 
> > > > > 大哥搞出来了吗
> > > > > 我想的是在config中把方法定义好，然后组件中以bus的方式监听
> > > 
> > > 
> > > 大哥你是这么写的吗？
> > > ![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
> > > 你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的
> > 
> > 
> > 你看他的example，https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue
> 
> 好了
> 
> ```
> item1['on-success'] = (response, file, fileList) => {
> 							if (response.success == "true") {
> 								item1['file-list'] = ([{
> 									name: '文件',
> 									url: response.msg
> 								}])
> 								this.$refs.parser.$refs.elForm.model[item1.fieldAlias] = response.msg
> 							}
> 						}
> ```

请问具体是怎么实现的,事件是在哪里绑定的,事件的方法是在哪里写的?

**Comment by zhangluJs** [comment]
> > > > > 基于这个项目二次开发的，请问关于事件的绑定有没有好点的思路
> > > > 
> > > > 
> > > > 大哥搞出来了吗
> > > > 我想的是在config中把方法定义好，然后组件中以bus的方式监听
> > 
> > 
> > 大哥你是这么写的吗？
> > ![image](https://user-images.githubusercontent.com/46159623/120057369-28042900-c075-11eb-820c-66cc66a51747.png)
> > 你能渲染的时候拿到吗？ 我直接存不了啊，如果直接等于这个配置是好使的
> 
> 你看他的example，https://github.com/JakHuang/form-generator/blob/dev/src/components/parser/example/Index.vue

大佬你好，我本地demo运行作者的example相关代码，事件无法触发，绑不上值是为什么
