### ISSUE TITLE
表单显示时 el-upload 怎么回显数据

### ISSUE THREAD

**Issue by yiyoxy** [JakHuang/form-generator#153]
form-generator 制作并保存了表单 json，表单运行时 el-upload选择文件上传 能正常显示 并且能上传成功。查看表单信息时  formjson 和 formdata 都有值，但el-upload并不能回显图片。 #125 按照这个修改，也不能显示 数据库 查询出来的图片。求教。

**Comment by JakHuang** [comment]
[参考示例代码](https://github.com/JakHuang/form-generator/blob/master/src/components/parser/example/Index.vue)
[效果预览](https://mrhj.gitee.io/form-generator/#/parser)

**Comment by yiyoxy** [comment]
我是在render.js里修改的，给file-list赋值。但如果上传了多张图片，vModel会执行多次，el-upload会渲染多次，有闪动现象，但好歹能回显 后台返回的图片了。
function vModel(dataObject, defaultValue, config) {
  if(config !== undefined && config !== null && config !== '' && config.tag === 'el-upload') {
    dataObject.attrs['on-success']= (response, file, fileList)=> {
      this.$emit('upload', response, file, fileList)
    }
    dataObject.attrs['on-remove']= (file, fileList)=> {
      this.$emit('deleteUpload', file, fileList)
    }
    if (defaultValue !== undefined && defaultValue !== null && defaultValue !=='') {
      dataObject.attrs['file-list'] = JSON.parse(defaultValue)
    }
    return
  }
  dataObject.props.value = defaultValue

  dataObject.on.input = val => {
    this.$emit('input', val)
  }
}

**Comment by cksspk** [comment]
> 我是在render.js里的，给文件列表修改的，但如果上传了很多图片，但如果上传了很多图片，el-upload会渲染多次，有返回效果，后台好歹能闪回显示。 function vModel (dataObject, defaultValue, config) { if(config !== undefined && config !== null && config !== '' && config.tag === 'el-upload') { dataObject. attrs['on-success']= (response, file, fileList)=> { this.$emit('upload', response, file, fileList) } dataObject.attrs['on-remove']= (file, fileList )=> { this.$emit('deleteUpload', file, fileList) } if (defaultValue !== undefined && defaultValue !== null && defaultValue !=='') { dataObject.attrs['file-list'] = JSON。解析（默认值） } 返回 } dataObject.props.value = defaultValue
> 
> dataObject.on.input = val => { this.$emit('input', val) } }

upload渲染多次怎么解决的？
