### ISSUE TITLE
增加栅格布局组件

### ISSUE THREAD

**Issue by WangHone** [JakHuang/form-generator#2]
希望作者增加栅格布局组件

**Comment by JakHuang** [comment]
提上日程



---原始邮件---
发件人: "WangHone"<notifications@github.com&gt;
发送时间: 2020年1月7日(周二) 上午8:12
收件人: "JakHuang/form-generator"<form-generator@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [JakHuang/form-generator] 增加栅格布局组件 (#2)



希望作者增加栅格布局组件

**Comment by JakHuang** [comment]
已经支持 [行容器实现](https://github.com/JakHuang/form-generator/commit/6fd9b950be4ea3aaa52ef96956392895a65f305a)
