### ISSUE TITLE
关于级联选择控件的一个Bug

### ISSUE THREAD

**Issue by MostWanted1** [JakHuang/form-generator#21]
选择【级联控件】，在最右侧【组件属性】面板的【选项】下面，将【数据类型】切换到【静态数据】，点击运行，可正常显示。当删除【静态数据】数据后，再点击运行，页面报错。
![QQ图片20200402233550](https://user-images.githubusercontent.com/15066349/78268386-b5fc8680-753a-11ea-9979-c21aca5b8ff7.png)

**Comment by JakHuang** [comment]
[已修复](https://github.com/JakHuang/form-generator/commit/1317341f607006d75619764cca529183f7d93e2c)
感谢
