### ISSUE TITLE
怎么将这个表单设计器作为一个页面引入项目

### ISSUE THREAD

**Issue by ZaccheoMoon** [JakHuang/form-generator#24]
小白求救

**Comment by JakHuang** [comment]
目前建议iframe引入

**Comment by ZaccheoMoon** [comment]
不太明白，我这用的是vue-element-admin，而且需要得到JSON和Vue的表单配置数据，需要一个getJson和getVue的方法，另外就是得到的单选或者多选框不知道怎么让它们动态获取options

**Comment by hzjzxp** [comment]
支持运行期间动态加载 json文件生成表单吗？

**Comment by guanpenghui1993** [comment]
> 不太明白，我这用的是vue-element-admin，而且需要得到JSON和Vue的表单配置数据，需要一个getJson和getVue的方法，另外就是得到的单选或者多选框不知道怎么让它们动态获取options

弄好了吗？
