### ISSUE TITLE
html引用生成的.vue文件

### ISSUE THREAD

**Issue by asister** [JakHuang/form-generator#3]
html中使用httpVueLoader加载.vue没有效果，使用普通的vue文件可以成功

**Comment by JakHuang** [comment]
是的，现在还不支持引入插件，因为项目产出的代码是一个Vue单文件。后面会支持引入资源



---原始邮件---
发件人: "asister"<notifications@github.com&gt;
发送时间: 2020年1月7日(周二) 上午9:57
收件人: "JakHuang/form-generator"<form-generator@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [JakHuang/form-generator] html引用生成的.vue文件 (#3)



html中使用httpVueLoader加载.vue没有效果，使用普通的vue文件可以成功

**Comment by JakHuang** [comment]
![image](https://user-images.githubusercontent.com/14212588/72217145-9a9a6480-3565-11ea-811e-a5ee488bd8c6.png)
代码生成器生成的脚步是通过export default返回对象的。而httpVueLoader模式只能识别module.exports返回的对象。有需要的同学请参阅：
https://github.com/FranckFreiburger/http-vue-loader/issues/89

**Comment by JakHuang** [comment]
httpVueLoader加载.vue需要自行引入外部资源。目前已经支持，详见：
https://github.com/JakHuang/form-generator/commit/187ded36ba2912ff33a9f9436c98c99b95b7c524
