### ISSUE TITLE
作者你好，我认真的去看了你的代码，然后自己去模仿了一下，但是我发现了一个问题，就是el-checkbox-group无法选择的问题。

### ISSUE THREAD

**Issue by whenTheMorningDark** [JakHuang/form-generator#34]
![image](https://user-images.githubusercontent.com/30688843/81151855-f759d900-8fb3-11ea-8219-8ea9f6c81c69.png)
我也是使用value来进行绑定但是，会出现el-checkbox无法选中的bug,不知道你在开发的初期是怎么解决的？

**Comment by JakHuang** [comment]
根据你的描述，猜不出问题。el-checkbox-group要求赋值给数组。

**Comment by zhangluJs** [comment]
> ![image](https://user-images.githubusercontent.com/30688843/81151855-f759d900-8fb3-11ea-8219-8ea9f6c81c69.png) 我也是使用value来进行绑定但是，会出现el-checkbox无法选中的bug,不知道你在开发的初期是怎么解决的？

你好，我想问一下，你自己模仿的过程中有遇到psrse.vue 事件无法触发，值绑不上的问题吗
