### ISSUE TITLE
建议给出图标选择窗，直观选择

### ISSUE THREAD

**Issue by happy-panda** [JakHuang/form-generator#4]
![image](https://user-images.githubusercontent.com/26876130/71942201-689ca180-31f7-11ea-994c-d6d01bc8f0cc.png)
建议给出图标选择窗，直观选择

**Comment by JakHuang** [comment]
已纳入计划

**Comment by JakHuang** [comment]
已经支持直接选择，详见：https://github.com/JakHuang/form-generator/commit/ec9c5a2f68380fdac95be031621ca082607e57a7
