### ISSUE TITLE
建议：支持批量添加组件

### ISSUE THREAD

**Issue by happy-panda** [JakHuang/form-generator#5]
例如，提供一个文本输入框，每换行表示一个字段，批量生成组件，默认使用输入框。然后每个组件上再做一个切换组件类型的功能，完美！

**Comment by JakHuang** [comment]
有过类似的设想。我是想从一个接口获取数据去渲染表单的。然后就到你问题描述的操作了。先纳入计划吧。

**Comment by happy-panda** [comment]
> 有过类似的设想。我是想从一个接口获取数据去渲染表单的。然后就到你问题描述的操作了。先纳入计划吧。

其实没必要弄接口查数据库，因为实际使用中，我的库不一定让你连，但是把数据库的字段copy出来是很简单方便的事情
