### ISSUE TITLE
关于Home.vue页面的数据渲染问题

### ISSUE THREAD

**Issue by getvkey** [JakHuang/form-generator#57]
@JakHuang 你好
* 数据json我是存在数据库，打开构建器页面时不使用LocaStorage和默认的drawingDefalut.js
* 而是请求接口里面有fields组件数组和form表单属性参数(就是点击生成json的数据)
* 我在created里面调用该接口，但渲染时出现异步加载问题，那些activeData，activeId都是在属性里面已经选择下标0第一个
* 刚接触这块，有时间看到请指教下。谢谢！

**Comment by getvkey** [comment]
@JakHuang 不好意思，已经解决了，想说删除这个issues，第一次提交这个发现删除不了，无视就好。。。

**Comment by tony2y** [comment]
@getvkey 我也遇到这个问题 ，请问有解决方式吗

**Comment by getvkey** [comment]
@tony2y 我是这样的： mounted() 请求后端接口用async await 或者setTimeout，渲染时用到了this.$nextTick

**Comment by jinxiaoxin** [comment]
@getvkey  可以把相关代码贴上来学习下不？
