### ISSUE TITLE
为form-generator编写vscode插件

### ISSUE THREAD

**Issue by JakHuang** [JakHuang/form-generator#6]
封装一个vscode插件，让form-generator拥有写入文件的能力。

**Comment by JakHuang** [comment]
已经完成，详见：https://github.com/JakHuang/form-generator-plugin

**Comment by chqfly** [comment]
vscode拖拽功能使用不了？你们的可以吗？

**Comment by zxl56123** [comment]
我的今天第一次使用，拖拽功能也用不了
Version: 1.55.2 (Universal)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (2 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by chqfly** [comment]
> 我的今天第一次使用，拖拽功能也用不了
> Version: 1.55.2 (Universal)
> Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
> Date: 2021-04-13T09:36:32.643Z (2 days ago)
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Darwin x64 19.6.0

应该是webview中使用了iframe，对iframe操作做了一些限制。经过验证如果直接使用webview，拖拽是没有问题的

**Comment by tom-hanks** [comment]
> > 我的今天第一次使用，拖拽功能也用不了
> > 版本：1.55.2（通用）
> > 提交：3c4e3df9e89829dce27b7b5c24508306b151f30d
> > 日期：2021-04-13T09：36：32.643Z（2天前）
> > 电子：11.3.0
> > 铬：87.0 .4280.141 
> > Node.js：12.18.3 
> > V8：8.7.220.31-electron.0
> > 操作系统：Darwin x64 19.6.0
> 
> 应该是webview中使用了iframe，对iframe操作了一些限制。 经过验证如果直接使用webview，拖拽是没有问题的

那请问 怎么解决这个问题呢
