### ISSUE TITLE
按照表单设计器 · 开发教程添加的按钮组件，报错了，怎么解决，谢谢

### ISSUE THREAD

**Issue by Mr-zhangbaofeng** [JakHuang/form-generator#61]
![image](https://user-images.githubusercontent.com/66286364/89405694-937bb380-d74e-11ea-840b-42e21088691e.png)
![image](https://user-images.githubusercontent.com/66286364/89405728-9d051b80-d74e-11ea-920b-ce2b51be003a.png)
![image](https://user-images.githubusercontent.com/66286364/89405778-ac846480-d74e-11ea-938b-5df9900b3705.png)

**Comment by JakHuang** [comment]
svg加载需配置（webpack）svg-sprite-loader
