### ISSUE TITLE
级联编辑器增加单选功能

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [JakHuang/form-generator#63]
我看element官方文档有这个功能，就是级联编辑器的任一节点的单选功能。

比如做CMS，发布文章，要选分类，可以选大类也可以选小类。

希望增加这个功能。

**Comment by JakHuang** [comment]
已添加。
https://github.com/JakHuang/form-generator/commit/6033fb3bad1efa7ef84dc3fbd32dfb01094810e3
如需更多属性可尝试自己添加。
