### ISSUE TITLE
Parser组件中的配置JSON如何异步加载

### ISSUE THREAD

**Issue by musicguoke** [JakHuang/form-generator#66]
您好，现在我的项目出现一个问题，在使用到Parser组件时需要异步加载JSON 配置问题件，请问这问题该如何解决

**Comment by musicguoke** [comment]
现在这个问题我已经解决了，在对formConf 赋值之后调用 $forceUpdate() ， 如果有更好的方法请指点一下

**Comment by konnga** [comment]
请问有示例代码吗？

**Comment by musicguoke** [comment]
你可以看看

**Comment by tony2y** [comment]
同求这个问题的解决方式，后端返回json  加载后无法解析。赋值不成功

**Comment by musicguoke** [comment]
> 同求这个问题的解决方式，后端返回json 加载后无法解析。赋值不成功

你核对一下你返回的json,看看是否和生成器生成的格式一致.

**Comment by konnga** [comment]
如果是数据正确，那可以在parser中，watch监听formConf，然后再对formConfCopy赋值
![Uploading 图片.png…]()
