### ISSUE TITLE
上传组件怎么处理数据？

### ISSUE THREAD

**Issue by zw12579** [JakHuang/form-generator#70]
上传后的数据怎么处理，怎么放入表单数据和数据回显

**Comment by 423343690** [comment]
引用的render.js中vModel方法增加上传控件的判断
function vModel(dataObject, defaultValue,config) {

  if(config.tag === 'el-upload')
  {


    //增加上传回调事件
    dataObject.attrs['on-success']= (response, file, fileList)=> {
    this.$emit('upload', response, file, fileList)
    }

    dataObject.attrs['on-remove']= (file, fileList)=> {
      this.$emit('deleteUpload', file, fileList)
      }
  }
  else{
    dataObject.props.value = defaultValue
    dataObject.on.input = val => {
    this.$emit('input', val)
    }
  }
}

然后在 Parser.vue中出发回调时赋值
function setUpload(event, config, scheme,response, file, fileList) {

      var newValue =JSON.parse(this[this.formConf.formModel][scheme.__vModel__])
  
      newValue.push({name:file.name, url:response.newPath})

      this.$set(config, 'defaultValue', JSON.stringify(newValue))
      this.$set(this[this.formConf.formModel], scheme.__vModel__, JSON.stringify(newValue))
}

function deleteUpload(event, config, scheme,file,fileList) {
  var newValue = []
  fileList.forEach(element => {
    newValue.push({name:element.name, url:element.url})
  });
     this.$set(config, 'defaultValue', JSON.stringify(newValue))
    this.$set(this[this.formConf.formModel], scheme.__vModel__, JSON.stringify(newValue))
}

**Comment by zw12579** [comment]
谢了，我自己改了源码，思路跟你这个差不多，不过是在porps上做的文章

**Comment by kill136** [comment]
非常感谢，学习啦

**Comment by kill136** [comment]
> 引用的render.js中vModel方法增加上传控件的判断
> function vModel(dataObject, defaultValue,config) {
> 
> if(config.tag === 'el-upload')
> {
> 
> ```
> //增加上传回调事件
> dataObject.attrs['on-success']= (response, file, fileList)=> {
> this.$emit('upload', response, file, fileList)
> }
> 
> dataObject.attrs['on-remove']= (file, fileList)=> {
>   this.$emit('deleteUpload', file, fileList)
>   }
> ```
> 
> }
> else{
> dataObject.props.value = defaultValue
> dataObject.on.input = val => {
> this.$emit('input', val)
> }
> }
> }
> 
> 然后在 Parser.vue中出发回调时赋值
> function setUpload(event, config, scheme,response, file, fileList) {
> 
> ```
>   var newValue =JSON.parse(this[this.formConf.formModel][scheme.__vModel__])
> 
>   newValue.push({name:file.name, url:response.newPath})
> 
>   this.$set(config, 'defaultValue', JSON.stringify(newValue))
>   this.$set(this[this.formConf.formModel], scheme.__vModel__, JSON.stringify(newValue))
> ```
> 
> }
> 
> function deleteUpload(event, config, scheme,file,fileList) {
> var newValue = []
> fileList.forEach(element => {
> newValue.push({name:element.name, url:element.url})
> });
> this.$set(config, 'defaultValue', JSON.stringify(newValue))
> this.$set(this[this.formConf.formModel], scheme.**vModel**, JSON.stringify(newValue))
> }

您好 我按照您的代码 试了一下，指定了默认值，但是没有渲染，请问能否展示一下Parser 源码
![image](https://user-images.githubusercontent.com/22001343/111071790-be16c180-8512-11eb-8c25-325ccc95ce9b.png)

**Comment by kill136** [comment]
> 谢了，我自己改了源码，思路跟你这个差不多，不过是在porps上做的文章

您好，我也遇到这个问题了，楼上 的方法，我试了貌似不行，您能分享一下解决方法吗？

**Comment by ZHANGBADAO** [comment]
代码如下

**修改render.js**
function vModel(dataObject, defaultValue, config) {
  //获取上传表单元素组件 上传的文件
  if(config.tag === 'el-upload'){
    // 上传表单元素组件 的成功和移除事件;
    dataObject.attrs['on-success']= (response, file, fileList)=> {
      this.$emit('upload', response, file, fileList)
    }

    dataObject.attrs['on-remove']= (file, fileList)=> {
      this.$emit('deleteUpload', file, fileList)
    }

    return
  }

  //获取 普通表单元素的值
  dataObject.props.value = defaultValue
  dataObject.on.input = val => {
    this.$emit('input', val)
  }
}



**修改parser.vue**
//给表单元素绑定事件
function buildListeners(scheme) {
  const config = scheme.__config__
  const methods = this.formConf.__methods__ || {}
  const listeners = {}

  // 给__methods__中的方法绑定this和event
  Object.keys(methods).forEach(key => {
    listeners[key] = event => methods[key].call(this, event)
  })

  // 响应 render.js 中的 vModel $emit('input', val)
  listeners.input = event => setValue.call(this, event, config, scheme)
  //上传表单元素组件的成功和移除事件;
  listeners.upload = (response, file, fileList) => setUpload.call(this, config, scheme,response, file, fileList)
  listeners.deleteUpload = (file, fileList) => deleteUpload.call(this, config, scheme,file, fileList)

  return listeners
}

//获取上传表单元素组件 上传的文件
function setUpload(config, scheme, response, file, fileList) {
  //response: 上传接口返回的数据
  let fileObj = {name: response.data.name, url: response.data.url, fileType: response.data.contentType}
  let oldValue = JSON.parse(this[this.formConf.formModel][scheme.__vModel__])
  if (oldValue) {
    oldValue.push(fileObj)
  } else {
    oldValue = [fileObj]
  }

  this.$set(config, 'defaultValue', JSON.stringify(oldValue))
  this.$set(this[this.formConf.formModel], scheme.__vModel__, JSON.stringify(oldValue))
}
//获取上传表单元素组件 删除文件后的文件列表
function deleteUpload(config, scheme, file, fileList) {
  let oldValue = JSON.parse(this[this.formConf.formModel][scheme.__vModel__])

  //file 删除的文件
  //过滤掉删除的文件
  let newValue = oldValue.filter(item => item.name !== file.name)
  this.$set(config, 'defaultValue', JSON.stringify(newValue))
  this.$set(this[this.formConf.formModel], scheme.__vModel__, JSON.stringify(newValue))
}

**Comment by yiyoxy** [comment]
on-success 和 on-remove 是 上传时触发的事件。如果是后台返回的数据，还是显示不出来。求教。

**Comment by xinchanghao** [comment]
@kill136 我在这个项目里提了个pr，解决了问题，https://gitee.com/tony2y/RuoYi-flowable/pulls/10
