### ISSUE TITLE
Could not read source map

### ISSUE THREAD

**Issue by fhadd** [JakHuang/form-generator#78]
我在断点调试的时候，提示 Could not read source map for http://lib.baomitu.com/js-beautify/1.10.2/beautifier.min.js: Unexpected token < in JSON at position 0
请问一下 是什么原因
VSCode 
![image](https://user-images.githubusercontent.com/4043854/99376069-6ae38800-28ff-11eb-9d62-2a7d91ae0794.png)
![image](https://user-images.githubusercontent.com/4043854/99376180-8c447400-28ff-11eb-827f-d9bde266f88c.png)

**Comment by JakHuang** [comment]
js-beautify的source map文件缺失，cdn资源的问题。不会有任何影响的。
